name: Send Deployment Notification

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      status:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print Notification
        run: |
          echo "Sending notification: Deployment to ${{ inputs.environment }} was a ${{ inputs.status }}"